### ISSUE TITLE
The .csproj project of aspnetcore needs to be updated to support docker building out of the box

### ISSUE THREAD

**Issue by Arash-Sabet** [LegacyTemplates/angular-spa#1]
When scaffolding an aspnetcore app for service fabric mesh, the csproj file generated out of the template does not contain the necessary entries to build and run an error-free docker container. 

The following entries need to be added to the csproj files to address the problem of including "dist" folder in the final docker container:

```xml
  <Target Name="NgDebug" BeforeTargets="Build" Condition="'$(Configuration)' == 'Debug'">
    <Exec WorkingDirectory="$(ProjectDir)ClientApp" Command="ng build -ec" />
  </Target>
  <Target Name="NgRelease" BeforeTargets="Build" Condition="'$(Configuration)' == 'Release'">
    <Exec WorkingDirectory="$(ProjectDir)ClientApp" Command="ng build --prod" />
  </Target>
```

**Comment by mythz** [comment]
The templates don't have a `ClientApp` folder, do you mean `/src`?

Don't want to pollute the templates to include workarounds for specific providers but I've listed it in the troubleshooting section of the docs: https://github.com/NetCoreTemplates/angular-spa#troubleshooting
